apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | trunc 26 }}-maintenance-tasks
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '5 2 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            reportuploader: cronjob
        spec:
          containers:
          - name: maintenance-tasks
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['rake', "maintenance:tasks"]
{{ include "app.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 500m
                memory: 2048Mi
              requests:
                cpu: 200m
                memory: 1024Mi
          restartPolicy: Never
