apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKeyBase: {{ .Values.deploy.secretKeyBase | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{end}}
  sentryDsn: {{ .Values.sentry.dsn | b64enc | quote }}
  useTestThresholdData: {{ .Values.threshold.useTestData | b64enc | quote }}
  legalFrameworkApiHost:  {{ .Values.legalFrameworkApi.host | b64enc | quote }}
  sentryEnabled: {{ .Values.sentry.enabled | b64enc | quote }}
  notificationsApiKey: {{ .Values.notifications.apiKey | b64enc | quote }}
  notificationsErrorMessageTemplateId: {{ .Values.notifications.errorMessageTemplateId | b64enc | quote }}
  notificationsRecipient: {{ .Values.notifications.recipient | b64enc | quote }}
