require:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/HashSyntax:
  Exclude:
    - 'spec/factories/gross_income_summary_factory.rb'
    - 'spec/integration/policy_disregards_spec.rb'
    - 'spec/integration/remarks_spec.rb'

# **** LEAVE FOR NOW ****
RSpec/ContextWording:
  Enabled: false

# Swagger docs specs use `run_test!` method to dynamically generate
# a test and generate yaml. Rubocop does not recognize as a test.
RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/swagger_docs/**/*

RSpec/ScatteredSetup:
    Exclude:
    - spec/requests/swagger_docs/**/*

# ****
# **** Removing this will break specs.  It removes all the explicit subject declarations that it thinks aren't necessary, but doesn't always get it right.
# **** Better to leave the explicit subject declarations in.  May be fixed when all Rspec/NamedSubject offences are fixed.
# ****
RSpec/LeadingSubject:
  Enabled: false

# **** Leave these - they are historic migrations and no purpose is solved by changing them
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20200102101936_refactor_disposable_income_summaries.rb'
    - 'db/migrate/20200420132900_add_fields_to_gross_income_summary.rb'
    - 'db/migrate/20210412102115_add_version_proceeding_type_codes.rb'
    - 'db/migrate/20211110163830_add_gross_earned_income_to_gross_income_summary.rb'
    - 'db/migrate/20211117161654_update_fields_on_employment.rb'
    - 'db/migrate/20211207112406_add_additional_fields_to_summaries.rb'
    - 'db/migrate/20220816154714_drop_proceeding_and_matter_from_assessments.rb'


# **** leave this - it is wrongly diagnosing an error
Rake/DuplicateTask:
  Exclude:
    - 'Rakefile'
    - 'lib/tasks/cucumber.rake'

Rails/FilePath:
  Exclude:
    - 'lib/tasks/cucumber.rake'

Rake/Desc:
  Exclude:
    - 'lib/tasks/cucumber.rake'
