SCHEMA_COMPONENTS = {
  assessment: "#/components/schemas/Assessment",
  applicant: "#/components/schemas/Applicant",
  proceeding_types: "#/components/schemas/ProceedingTypes",
  capitals: "#/components/schemas/Capitals",
  cash_transactions: "#/components/schemas/CashTransactions",
  dependant: "#/components/schemas/Dependant",
  employments: "#/components/schemas/Employments",
  irregular_income_payments: "#/components/schemas/IrregularIncomePayments",
  other_incomes: "#/components/schemas/OtherIncomes",
  outgoings_list: "#/components/schemas/OutgoingsList",
  regular_transaction: "#/components/schemas/RegularTransaction",
  state_benefit: "#/components/schemas/StateBenefit",
  vehicle: "#/components/schemas/Vehicle",
  employment_details: "#/components/schemas/EmploymentDetails",
  self_employment: "#/components/schemas/SelfEmployment",
  explicit_remarks: "#/components/schemas/ExplicitRemarks",
  capital_result: "#/components/schemas/CapitalResult",
  property_result: "#/components/schemas/PropertyResult",
  employment_payment_list: "#/components/schemas/EmploymentPaymentList",
  disposable_income: "#/components/schemas/DisposableIncome",
  property: "#/components/schemas/Property",
  proceeding_type_result: "#/components/schemas/ProceedingTypeResult",
  non_property_asset: "#/components/schemas/NonPropertyAsset",
}.freeze
