default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: cfe_civil_development
  request_log:
    <<: *default
    database_tasks: false
    host: localhost
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    database: <%= ENV['POSTGRES_DATABASE'] %>
    port: <%= ENV['POSTGRES_PORT'] %>

test:
  primary:
    <<: *default
    database: cfe_civil_test
  request_log:
    <<: *default
    database_tasks: false
    database: cfe_civil_test

production:
  primary:
    <<: *default
    host: <%= ENV['POSTGRES_HOST'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    database: <%= ENV['POSTGRES_DATABASE'] %>
  request_log:
    <<: *default
    database_tasks: false
    host: <%= ENV['POSTGRES_HOST'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    database: <%= ENV['POSTGRES_DATABASE'] %>
