# Default values for cfe-civil production
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 200Mi

ingress:
  className: modsec
  hosts:
    - cfe-civil.cloud-platform.service.justice.gov.uk
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "cfe-civil-cfe-civil-production-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On

deploy:
  host: cfe-civil.cloud-platform.service.justice.gov.uk

postgresql:
  enabled: false

legalFrameworkApi:
  host: http://legal-framework-api.legal-framework-api-production.svc.cluster.local

sentry:
  enabled: enabled

threshold:
  futureFile: ''
