---
gross_income_upper: 2657
infinite_gross_income_upper: 999_999_999_999
gross_income:
  dependant_step: 222
  dependant_increase_starts_after: 4
disposable_income_lower_certificated: 315
disposable_income_lower_controlled: 733
disposable_income_upper: 733
disposable_income_certificated_immigration_asylum_upper_tribunal: 733
capital_lower_certificated: 3_000
capital_upper: 8_000
capital_immigration_first_tier_tribunal_controlled: 3_000
capital_immigration_upper_tribunal_certificated: 3_000
capital_asylum_upper_tribunal_certificated: 8_000
partner_allowance: 191.41
pensioner_capital_disregard:
  minimum_age_in_years: 60
  passported: 100_000
  non_passported: 100_000
  # capital to disregard if monthly disposable income (excluding income derived from capital) is below these figures
  monthly_income_values:
    [-.inf, 25.00]: 100_000
    [25.01, 50.00]: 90_000
    [50.01, 75.00]: 80_000
    [75.01, 100.00]: 70_000
    [100.01, 125.00]: 60_000
    [125.01, 150.00]: 50_000
    [150.01, 175.00]: 40_000
    [175.01, 200.00]: 30_000
    [200.01, 225.00]: 20_000
    [225.01, 315.00]: 10_000
    [315.01, .inf]: 0
property_notional_sale_costs_percentage: 3.0
property_maximum_mortgage_allowance: 999_999_999_999
property_disregard:
  main_home: 100_000.0
  additional_property: 0.0
vehicle_disregard: 15_000
vehicle_out_of_scope_months: 36

dependant_allowances:
  child_under_15: 307.64
  child_aged_15: 307.64
  child_16_and_over: 307.64
  adult: 307.64
  adult_capital_threshold: 8_000

single_monthly_housing_costs_cap: 545

disposable_income_contribution_bands:
  bands:
    band_zero:
      threshold: -.inf
      disregard: 0.0
      percentage: 0.0
      base: 0.0
    band_a:
      threshold: 315.0
      disregard: 311.0
      percentage: 35.0
      base: 0
    band_b:
      threshold: 466
      disregard: 465
      percentage: 45.0
      base: 53.90
    band_c:
      threshold: 617
      disregard: 616
      percentage: 70.0
      base: 121.85
  minimum_contribution: 0.0

fixed_employment_allowance: 45.0
employment_income_variance: 60.0
subject_matter_of_dispute_disregard: 100000.0
