name: Brakeman Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  brakeman:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/brakeman.yml@df9a4a8ad625a391c27ccf81a1c1a2d7b23e6474 # main as of 24/06/2026
