name: Brakeman Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  brakeman:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/brakeman.yml@932ee576d65d9992ca82955a5823e3d55e888417 # main as of 28/07/2026
